import { Lato } from 'next/font/google'

import './globals.css'
import Header from './Header'
import Sidebar from './Sidebar';

const lato = Lato({
  weight: '400',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lato.className} bg-offwhite`}>
        <div className="flex relative overflow">
          <Sidebar />
          <div className="overflow-x-auto relative">
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
