import './globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <header class="sticky top-0 text-center w-full">
          <div class="container mx-auto">
            <div>Uptown Alive</div>
            <nav>
              <ul class="list-none flex">
                <li>home</li>
                <li>news</li>
                <li>businesses</li>
              </ul>
            </nav>
          </div>
        </header>
        <main>{children}</main>
      </body>
    </html>
  )
}
